// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Account struct {
	ID        int32
	Number    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
