// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Account struct {
	ID        int32
	Number    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OperationType struct {
	ID          int32
	Description string
	Mode        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Transaction struct {
	ID              int32
	Amount          float64
	AccountID       int32
	OperationTypeID int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
