// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: operation_types.sql

package database

import (
	"context"
)

const getOperationById = `-- name: GetOperationById :one
SELECT id, description, mode, created_at, updated_at FROM operation_types WHERE id = $1
`

func (q *Queries) GetOperationById(ctx context.Context, id int32) (OperationType, error) {
	row := q.db.QueryRowContext(ctx, getOperationById, id)
	var i OperationType
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
