// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package database

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions(account_id, operation_type_id, amount) VALUES($1, $2, $3)
RETURNING id, amount, account_id, operation_type_id, created_at, updated_at
`

type CreateTransactionParams struct {
	AccountID       int32
	OperationTypeID int32
	Amount          float64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.AccountID, arg.OperationTypeID, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AccountID,
		&i.OperationTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
